version: '3.8'

services:
  mongodb:
    image: mongo:5.0
    container_name: event-management-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: event_management
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: event-management-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_HOST: mongodb
      SPRING_DATA_MONGODB_PORT: 27017
      SPRING_DATA_MONGODB_DATABASE: event_management
      SPRING_DATA_MONGODB_USERNAME: admin
      SPRING_DATA_MONGODB_PASSWORD: password
      JWT_SECRET: your-super-secret-jwt-key-that-should-be-very-long-and-secure-for-production-use
    depends_on:
      - mongodb
    volumes:
      - ./backend/src/main/resources/application.properties:/app/src/main/resources/application.properties:ro

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: event-management-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://localhost:8080/api
    depends_on:
      - backend

volumes:
  mongodb_data: